{
    "company_auto_shipment_insurance_setting": false,
    "covid_zones": {
        "delivery_zone": null,
        "pickup_zone": null
    },
    "currency": "INR",
    "data": {
        "available_courier_companies": [
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Not Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 33.8,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 82,
                "courier_name": "DTDC Surface 2kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 5,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 89.4,
                "id": 567858798,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 2,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"auto_pickup\":0,\"cancel_real_time\":true,\"from_file\":1,\"is_cancellation_courier\":1,\"is_custom_courier\":1,\"is_eway_bill_courier\":1,\"is_manual_courier\":1,\"is_notify_cancel_courier\":1,\"prefetch_awb\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.4,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "On Request",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 123.2,
                "rating": 4.8,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 89.4,
                "rto_performance": 4.8,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-03 19:15:05",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Not Available",
                "charge_weight": 2,
                "city": "Delhi NCR",
                "cod": 1,
                "cod_charges": 45.38,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 24,
                "courier_name": "Xpressbees Surface 2kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.6,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 101.68,
                "id": 566620998,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 2,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"fbs_amazon_Standard\":1,\"international_enabled\":1,\"is_cancellation_courier\":1,\"is_custom_courier\":0,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_manual_courier\":1,\"is_manual_prefecth_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"prefetch_awb\":1,\"prefetch_enabled\":0,\"qr_pickrr_enable\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.6,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 147.06,
                "rating": 4.7,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 81.32,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-01 18:11:04",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 4.6,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 45.4,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 170,
                "courier_name": "Ekart Surface 2kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "10:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.7,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 109,
                "id": 567706018,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 2,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"cancel_real_time\":true,\"is_cancellation_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.2,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "On Request",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 154.4,
                "rating": 4.7,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 69,
                "rto_performance": 4.7,
                "seconds_left_for_pickup": 34272,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-03 15:38:08",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 5,
                "volumetric_max_weight": 12,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 45.38,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 19,
                "courier_name": "Ecom Express Surface 2kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.6,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 83.04,
                "id": 564569685,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 2,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"international_enabled\":1,\"is_cancellation_courier\":1,\"is_custom_courier\":0,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.7,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 128.42,
                "rating": 4.6,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 83.04,
                "rto_performance": 4.5,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-03-25 19:21:01",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "30.00",
                "tracking_performance": 5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 5,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 45.38,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 298,
                "courier_name": "Ecom Express Surface 5kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.6,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "3",
                "etd": "Apr 10, 2025",
                "etd_hours": 72,
                "freight_charge": 170.1,
                "id": 564578185,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"is_cancel_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.7,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 215.48,
                "rating": 4.6,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 121,
                "rto_performance": 4.5,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-03-25 19:21:34",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "30.00",
                "tracking_performance": 5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Not Available",
                "charge_weight": 2,
                "city": "Delhi",
                "cod": 1,
                "cod_charges": 36,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 32,
                "courier_name": "Amazon Shipping Surface 2kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "09:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 3.9,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 88,
                "id": 567534888,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": false,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 2,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"auto_pickup\":1,\"cancel_real_time\":true,\"is_cancellation_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.4,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "On Request",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 124,
                "rating": 4.1,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 88,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 30672,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-02 22:38:18",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 2.4,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "Delhi",
                "cod": 1,
                "cod_charges": 48.2,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 637,
                "courier_name": "Shiprocket Surface",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.3,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "3",
                "etd": "Apr 10, 2025",
                "etd_hours": 72,
                "freight_charge": 137.9,
                "id": 554674547,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"cloned_from_courier_id\":43,\"courier_available_for_payment_change\":1,\"fbs_amazon_Standard\":1,\"international_enabled\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_notify_cancel_courier\":1,\"is_warehouse_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"qr_pickrr_enable\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.6,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 186.1,
                "rating": 4.6,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 146,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "Delhi",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-02-21 14:16:46",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 4.5,
                "volumetric_max_weight": 4,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "30.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 45.4,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 228,
                "courier_name": "Ecom Air 500gm",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.5,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 165.7,
                "id": 479870257,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": false,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 1,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"is_cancellation_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.7,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 211.1,
                "rating": 4.3,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 172,
                "rto_performance": 4.8,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": null,
                "surface_max_weight": "0.00",
                "tracking_performance": 3,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "32.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Not Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 38.2,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 196,
                "courier_name": "DTDC Air 500gm",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 5,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 178.1,
                "id": 567873798,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": false,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 1,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"auto_pickup\":0,\"cancel_real_time\":true,\"from_file\":1,\"is_cancellation_courier\":1,\"is_custom_courier\":1,\"is_eway_bill_courier\":1,\"is_manual_courier\":1,\"is_notify_cancel_courier\":1,\"prefetch_awb\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.4,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "On Request",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 216.3,
                "rating": 4.5,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 216.8,
                "rto_performance": 4.8,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-03 19:15:43",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "0.00",
                "tracking_performance": 3.4,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 22,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 338,
                "courier_name": "Shiprocket Next Day Delivery",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 5,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "1",
                "etd": "Apr 08, 2025",
                "etd_hours": 24,
                "freight_charge": 197,
                "id": 14710,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"is_cancel_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"ndd_courier\":1,\"sdd_courier\":0,\"sdd_ndd_attributes\":\"ndd\",\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.9,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 219,
                "rating": 4.9,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 192,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "2025-04-07",
                "suppress_text": "",
                "suppression_dates": null,
                "surface_max_weight": "30.00",
                "tracking_performance": 4.9,
                "volumetric_max_weight": 30,
                "weight_cases": 4.8,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 22,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 453,
                "courier_name": "Ecom Express Next day delivery",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 5,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "1",
                "etd": "Apr 08, 2025",
                "etd_hours": 24,
                "freight_charge": 209,
                "id": 14710,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"is_cancel_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"ndd_courier\":1,\"sdd_courier\":0,\"sdd_ndd_attributes\":\"ndd\",\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.9,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 231,
                "rating": 4.9,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 204,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "2025-04-07",
                "suppress_text": "",
                "suppression_dates": null,
                "surface_max_weight": "30.00",
                "tracking_performance": 4.9,
                "volumetric_max_weight": 30,
                "weight_cases": 4.8,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "Delhi",
                "cod": 1,
                "cod_charges": 52,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 43,
                "courier_name": "Delhivery Surface",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.3,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 199.51,
                "id": 567986359,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"fbs_amazon_Standard\":1,\"international_enabled\":1,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_notify_cancel_courier\":1,\"is_warehouse_courier\":1,\"is_webhook_courier\":1,\"qr_pickrr_enable\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.6,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 251.51,
                "rating": 4.6,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 209.8,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "Delhi",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-04 19:23:21",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 4.5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "25.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "Delhi",
                "cod": 1,
                "cod_charges": 52.9,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 10,
                "courier_name": "Delhivery Air",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.8,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "1",
                "etd": "Apr 08, 2025",
                "etd_hours": 24,
                "freight_charge": 198.71,
                "id": 567950859,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": false,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 1,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"fbs_amazon_Standard\":1,\"international_enabled\":1,\"is_cancel_courier\":1,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_notify_cancel_courier\":1,\"is_warehouse_courier\":1,\"is_webhook_courier\":1,\"qr_pickrr_enable\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.6,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 251.61,
                "rating": 4.9,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 209,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "Delhi",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-04 19:21:27",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "0.00",
                "tracking_performance": 5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "7.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 48.2,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 48,
                "courier_name": "Ekart Logistics Air",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "10:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.5,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 203.6,
                "id": 487689469,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": false,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 1,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"cancel_real_time\":true,\"is_cancellation_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.2,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "On Request",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 251.8,
                "rating": 4.4,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 203.6,
                "rto_performance": 5,
                "seconds_left_for_pickup": 34272,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2024-09-13 17:48:01",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "0.00",
                "tracking_performance": 3,
                "volumetric_max_weight": 23,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "DELHI",
                "cod": 1,
                "cod_charges": 49.6,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 54,
                "courier_name": "Ekart Logistics Surface",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "10:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 3.9,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 204.4,
                "id": 567698018,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"cancel_real_time\":true,\"is_cancellation_courier\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.2,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "On Request",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 254,
                "rating": 4.5,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 204.4,
                "rto_performance": 4.8,
                "seconds_left_for_pickup": 34272,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-03 15:37:41",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "4.00",
                "tracking_performance": 4.5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 5,
                "city": "Delhi",
                "cod": 1,
                "cod_charges": 66.05,
                "cod_multiplier": 0.03,
                "cost": "",
                "courier_company_id": 39,
                "courier_name": "Delhivery Surface 5kg",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Not Available",
                "delivery_performance": 4.8,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 214.9,
                "id": 568001859,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": true,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 5,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"fbs_amazon_Standard\":1,\"international_enabled\":1,\"is_cancel_courier\":1,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_notify_cancel_courier\":1,\"is_warehouse_courier\":1,\"is_webhook_courier\":1,\"qr_pickrr_enable\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.6,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 280.95,
                "rating": 4.5,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 214.9,
                "rto_performance": 4.1,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "Delhi",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-04 19:23:55",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "9.00",
                "tracking_performance": 5,
                "volumetric_max_weight": null,
                "weight_cases": 4.6,
                "zone": "z_a"
            },
            {
                "air_max_weight": "0.00",
                "assured_amount": 0,
                "base_courier_id": null,
                "base_weight": "",
                "blocked": 0,
                "call_before_delivery": "Available",
                "charge_weight": 2,
                "city": "Delhi NCR",
                "cod": 1,
                "cod_charges": 30.45,
                "cod_multiplier": 0.02,
                "cost": "",
                "courier_company_id": 411,
                "courier_name": "Shiprocket 250 gram",
                "courier_type": "0",
                "coverage_charges": 0,
                "cutoff_time": "11:00",
                "delivery_boy_contact": "Available",
                "delivery_performance": 4.9,
                "description": "",
                "edd": "",
                "entry_tax": 0,
                "estimated_delivery_days": "2",
                "etd": "Apr 09, 2025",
                "etd_hours": 48,
                "freight_charge": 358.4,
                "id": 566656998,
                "is_custom_rate": 0,
                "is_hyperlocal": false,
                "is_international": 0,
                "is_rto_address_available": false,
                "is_surface": true,
                "local_region": 1,
                "metro": 1,
                "min_weight": 0.25,
                "mode": 0,
                "new_edd": 1,
                "odablock": false,
                "other_charges": 0,
                "others": "{\"allow_postcode_auto_sync\":1,\"cancel_real_time\":true,\"courier_available_for_payment_change\":1,\"fbs_amazon_Standard\":1,\"is_custom_courier\":1,\"is_edd_courier\":1,\"is_eway_bill_courier\":1,\"is_manual_courier\":1,\"is_manual_prefecth_courier\":1,\"is_notify_cancel_courier\":1,\"is_webhook_courier\":1,\"min_breadth\":1,\"min_length\":1,\"prefetch_awb\":1,\"prefetch_enabled\":0,\"qr_pickrr_enable\":1,\"wec\":1}",
                "pickup_availability": "1",
                "pickup_performance": 4.9,
                "pickup_priority": "",
                "pickup_supress_hours": 0,
                "pod_available": "Instant",
                "postcode": "110055",
                "qc_courier": 0,
                "rank": "",
                "rate": 388.85,
                "rating": 4.9,
                "realtime_tracking": "Real Time",
                "region": 1,
                "rto_charges": 358.4,
                "rto_performance": 4.9,
                "seconds_left_for_pickup": 37872,
                "secure_shipment_disabled": false,
                "ship_type": 1,
                "state": "DELHI",
                "suppress_date": "Apr 07, 2025",
                "suppress_text": "",
                "suppression_dates": {
                    "action_on": "2025-04-01 18:13:08",
                    "blocked_fm": "",
                    "blocked_lm": ""
                },
                "surface_max_weight": "5.00",
                "tracking_performance": 4.9,
                "volumetric_max_weight": 5,
                "weight_cases": 4.6,
                "zone": "z_a"
            }
        ],
        "child_courier_id": null,
        "is_recommendation_enabled": 1,
        "promise_recommended_courier_company_id": null,
        "recommendation_advance_rule": 0,
        "recommendation_level": "default",
        "recommended_by": {
            "id": 6,
            "title": "Recommendation By Shiprocket"
        },
        "recommended_courier_company_id": 82,
        "shiprocket_recommended_courier_id": 82
    },
    "dg_courier": 0,
    "eligible_for_insurance": 0,
    "insurace_opted_at_order_creation": false,
    "is_allow_templatized_pricing": true,
    "is_latlong": 0,
    "is_old_zone_opted": false,
    "is_zone_from_mongo": true,
    "label_generate_type": 2,
    "on_new_zone": 0,
    "seller_address": [],
    "status": 200,
    "user_insurance_manadatory": false
}